# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
  params:
    header:
      logo:
        text: 'Li He'
  menu:
    main:
      - name: Bio
        url: '/en/#about'
        weight: 10
      - name: Papers
        url: '/en/#papers'
        weight: 11
      - name: Talks
        url: '/en/#talks'
        weight: 12
      - name: Experience
        url: '/en/experience/'
        weight: 20
      - name: Projects
        url: '/en/projects/'
        weight: 20
# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 学术个人主页
  params:
    description: 学术个人主页（Hugo Academic CV）
  menu:
    main:
      - name: 简介
        url: '/'
        weight: 10
      - name: 论文
        url: '/#papers'
        weight: 11
      - name: 报告
        url: '/#talks'
        weight: 12
      - name: 经历
        url: '/experience/'
        weight: 20
      - name: 项目
        url: '/projects/'
        weight: 20
